hbis/grails-app/domain/hbis/Patient.groovy
package hbis

class Patient { //change class name to Patient
	String mrn
	String firstName
	String middleInitial
	String lastName
	Gender gender
	Race race
	Date dateOfBirth
	Institution originInstitution
	
	static hasMany = [procedures: Procedure, consents:Consent]
	String toString() {
		"${mrn}" + " " + "${lastName}"
	}

    static constraints = {
		mrn(blank: false, unique: true, matches: /\d{9}/)  //Must be 9 digits
		firstName(nullable:true)
		middleInitial(nullable:true)
		lastName()
		gender(nullable:true)
		race(nullable:true)
		dateOfBirth(nullable:true)
		originInstitution(nullable:true)
    }
	
	static mapping = {
		procedures(sort:'procedureDate', order:'asc')
		consents(sort:'consentDate', order:'asc')
	}
}

hbis/grails-app/domain/hbis/Procedure.groovy
package hbis
import java.text.SimpleDateFormat

class Procedure {
	ProcedureName procedureName //was surgeryName
	SubProcedureName subProcedureName
	ProcedureType procedureType
	Date procedureDate = new Date().clearTime()
	Date endTimeOfProcedure //case results
	Date dateOfDeath
	Institution procedureEventInstitution
	String building
	String roomNumber //case results
	ProcurementResult procurementResult //case results
	Origin origin
	Integer patientAge
	AgeUnit patientAgeUnit
	YesNo chemoHistory
	String chemoHistoryComments
	YesNo radiationHistory
	String radiationHistoryComments
	String medComments //this may be tied to Chart Review entity later
	ChartReview chartReview
	Date dateCreated
	
	static belongsTo = [patient: Patient]
	static hasMany = [specimens: Specimen]
	//static hasOne = [chartReview: ChartReview]
	
	String toString() {
		def sdf = new SimpleDateFormat("MM/dd/yyyy")
		"${id}: " + "${sdf.format(procedureDate)}, ${procedureName}"
	}
	
	
	static constraints = {
		procedureDate()
		procedureType()
		procedureName()
		subProcedureName(nullable:true)
		procedureEventInstitution()
		procurementResult(nullable:true)
		patientAge(nullable:true, min: 0)
		patientAgeUnit(nullable:true)
		dateOfDeath(nullable:true)
		chemoHistory(nullable: true)
		radiationHistory(nullable: true)
		endTimeOfProcedure(nullable:true)
		chartReview(nullable:true)
		origin(nullable:true)
	}
	
	static mapping = {
		table 'clinical_procedure' 
		specimens(sort:'specimenChtnId', order:'asc')
	}
	
	Integer getNumberOfSubspecimens() {
		def numberOfSubspecimens = 0
		this.specimens.each { specimen ->
			numberOfSubspecimens += specimen.getNumberOfSubspecimens()
		}
		return numberOfSubspecimens
	}
}

hbis/grails-app/domain/hbis/ProcedureType.groovy
package hbis

class ProcedureType {
	String description
	
	String toString() {
		description
	}
	
    static constraints = {
    }
}

hbis/grails-app/controllers/hbis/ProcedureController.groovy
package hbis

import org.springframework.dao.DataIntegrityViolationException
import java.text.SimpleDateFormat
import org.codehaus.groovy.grails.plugins.jasper.JasperReportDef

class ProcedureController {

    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

    def index() {
        redirect(action: "list", params: params)
    }
	
	def jasperService
	def morningListReport() {
		def procedureDate = new Date().clearTime()
		def procedureCriteria = Procedure.createCriteria()
		def procedures = procedureCriteria.list {
			ge("procedureDate", procedureDate)
			eq("procedureEventInstitution", Institution.findByDescription("OSU"))
			order("endTimeOfProcedure", "asc")
		}
		params.procedureDate = procedureDate
		JasperReportDef reportDef = jasperService.buildReportDefinition(params, request.getLocale(), [data:procedures])
		// Non-inline reports (e.g. PDF)
		if (!reportDef.fileFormat.inline && !reportDef.parameters._inline)
		{
			response.setHeader("Content-disposition", "attachment; filename="+(reportDef.parameters._name ?: reportDef.name) + "." + reportDef.fileFormat.extension);
			response.contentType = reportDef.fileFormat.mimeTyp
			response.characterEncoding = "UTF-8"
			response.outputStream << reportDef.contentStream.toByteArray()
		}
		else
		{
			// Inline report (e.g. HTML)
			render(text: reportDef.contentStream, contentType: reportDef.fileFormat.mimeTyp, encoding: reportDef.parameters.encoding ? reportDef.parameters.encoding : 'UTF-8');
		}
	}

    def list(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        [procedureInstanceList: Procedure.list(params), procedureInstanceTotal: Procedure.count()]
    }
	
	def amProcedureList() {
		Date today = new Date().clearTime()
		def procedureCriteria = Procedure.createCriteria()
		def procedureInstanceList = procedureCriteria.list {
			ge("procedureDate", today)
			eq("procedureEventInstitution", Institution.findByDescription("OSU"))
			order("endTimeOfProcedure", "asc")
		}
		[procedureInstanceList: procedureInstanceList]
	}
	
	def caseResults() {
		Date today = new Date().clearTime()
		def procedureCriteria = Procedure.createCriteria()
		def procedureInstanceList = procedureCriteria.list { //Procedure.findAllByDateCreatedGreaterThanEquals(today)
			ge("procedureDate", today)
			eq("procedureEventInstitution", Institution.findByDescription("OSU"))
			order("endTimeOfProcedure", "asc")		
		}
		
		[procedureInstanceList: procedureInstanceList]
	}
	
	def searchCaseResults() {
		def sdf = new SimpleDateFormat("MM/dd/yyyy")
		def procedureDate
		def mrn = params.mrn
		def lastName = params.lastName
		def procedureCriteria = Procedure.createCriteria()
		def procedureInstanceList
		
		if(params.procedureDate) {
			procedureDate = sdf.parse(params.procedureDate)
		}
		
		if(procedureDate || mrn || lastName) {
			procedureInstanceList = procedureCriteria.list {
				if(procedureDate) {
					eq("procedureDate", procedureDate)
				}
				patient {
					if(mrn) {
						ilike("mrn", "%" + mrn + "%")
					}
					if(lastName) {
						ilike("lastName", "%" + lastName + "%")
					}
					
				}
				order("procedureDate", "asc")
			}
		}
		
		
		[procedureInstanceList: procedureInstanceList, procedureDate: params.procedureDate, mrn: params.mrn, lastName: params.lastName]
	}

    def create() {
		def procedureInstance = new Procedure(params)
		
		if(procedureInstance.patient.originInstitution) { //Bring the institution over from the parent Patient
			procedureInstance.procedureEventInstitution = procedureInstance.patient.originInstitution
		}
		else { //If no parent Patient institution, make it default to OSU
			def institutionOsu = Institution.findByDescription("OSU")
			procedureInstance.procedureEventInstitution = institutionOsu
		}
		if(!procedureInstance.patientAgeUnit) {
			procedureInstance.patientAgeUnit = AgeUnit.findByDescription("Years")
		}
		
		procedureInstance.chemoHistory = YesNo.findByDescription("Unknown")
		procedureInstance.radiationHistory = YesNo.findByDescription("Unknown")
		
        [procedureInstance: procedureInstance, patientInstance:procedureInstance.patient]
    }

    def save() {
        def procedureInstance = new Procedure(params)
		procedureInstance.clearErrors()
		
		if(params.procedureDate) {
			def error = false
			def sdf = new SimpleDateFormat("MM/dd/yyyy")
			if(!(params.procedureDate.length() == 10)) {
				error = true
			}
			else {
				try {
					procedureInstance.procedureDate = sdf.parse(params.procedureDate)
				} catch (Exception e) { // Unable to parse procedureDate
					error = true
				}
			}
			if(error) {
				procedureInstance.errors.rejectValue("procedureDate", "validation.procedure.procedureDate.unparsable",
					[message(code: 'procedure.label', default: 'Procedure')] as Object[],
					"Procedure Date must be in MM/dd/yyyy format (example: 01/01/2014)")
				render(view: "create", model: [procedureInstance: procedureInstance, patientInstance:procedureInstance.patient])
				return
			}
		}
		if(params.endTimeOfProcedure) {
			def error = false
			if(!(params.endTimeOfProcedure.length() == 4)) { //There is unexpected behavior if given all numbers with greater than 4 length
				error = true
			}
			else {
				def sdf = new SimpleDateFormat("HHmm")
				try {
					procedureInstance.endTimeOfProcedure = sdf.parse(params.endTimeOfProcedure)
				} catch (Exception e) { // Unable to parse endTime
					error = true
				}
			}
			if(error) {
				procedureInstance.errors.rejectValue("endTimeOfProcedure", "validation.procedure.endTimOfProcedure.unparsable",
					[message(code: 'procedure.label', default: 'Procedure')] as Object[],
					"End Time must be in HHmm format (example: 1452)")
				render(view: "create", model: [procedureInstance: procedureInstance, patientInstance:procedureInstance.patient])
				return
			}
		}
		if(params.dateOfDeath) {
			def sdf = new SimpleDateFormat("MM/dd/yyyy")
			def error = false
			if(!(params.dateOfDeath.length() == 10)) {
				error = true
			}
			else {
				try {
					procedureInstance.dateOfDeath = sdf.parse(params.dateOfDeath)
				} catch (Exception e) { // Unable to parse procedureDate
					error = true
				}
			}
			if(error) {
				procedureInstance.errors.rejectValue("dateOfDeath", "validation.procedure.dateOfDeath.unparsable",
					[message(code: 'procedure.label', default: 'Procedure')] as Object[],
					"Date of Death must be in MM/dd/yyyy format (example: 01/01/2014)")
				render(view: "create", model: [procedureInstance: procedureInstance, patientInstance:procedureInstance.patient])
				return
			}
		}
		
        if (!procedureInstance.save(flush: true)) {
			def patientInstance = procedureInstance.patient
            render(view: "create", model: [procedureInstance: procedureInstance, patientInstance:patientInstance])
            return
        }

        flash.message = message(code: 'default.created.message', args: [message(code: 'procedure.label', default: 'Procedure'), procedureInstance.id])
		// Depending on which button is pressed, redirect to the appropriate place
		if(params.saveAndReturnAmProcedureList) {
			redirect(action: "amProcedureList")
			return
		}
		if(params.saveAndCreateSpecimen) {
			redirect(controller:"specimen", action: "create", params:['procedure.id': procedureInstance.id])
			return
		}
		if(params.saveAndCreateChartReview) {
			redirect(controller:"chartReview", action: "create", params:['procedure.id': procedureInstance.id])
			return
		}
		redirect(action: "show", id: procedureInstance.id)
    }
	
    def show(Long id) {
        def procedureInstance = Procedure.get(id)
        if (!procedureInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'procedure.label', default: 'Procedure'), id])
            redirect(action: "list")
            return
        }
		def patientInstance = procedureInstance.patient

        [procedureInstance: procedureInstance, patientInstance: patientInstance]
    }

    def edit(Long id) {
        def procedureInstance = Procedure.get(id)
        if (!procedureInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'procedure.label', default: 'Procedure'), id])
            redirect(action: "list")
            return
        }
		def patientInstance = procedureInstance.patient

        [procedureInstance: procedureInstance, patientInstance: patientInstance, view: params.view]
    }

    def update(Long id, Long version) {
        def procedureInstance = Procedure.get(id)
        if (!procedureInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'procedure.label', default: 'Procedure'), id])
            redirect(action: "list")
            return
        }

        if (version != null) {
            if (procedureInstance.version > version) {
                procedureInstance.errors.rejectValue("version", "default.optimistic.locking.failure",
                          [message(code: 'procedure.label', default: 'Procedure')] as Object[],
                          "Another user has updated this Procedure while you were editing")
                render(view: "edit", model: [procedureInstance: procedureInstance, patientInstance:procedureInstance.patient])
                return
            }
        }

        procedureInstance.properties = params
		procedureInstance.clearErrors()
		
		if(params.procedureDate) {
			def error = false
			def sdf = new SimpleDateFormat("MM/dd/yyyy")
			if(!(params.procedureDate.length() == 10)) {
				error = true
			}
			else {
				try {
					procedureInstance.procedureDate = sdf.parse(params.procedureDate)
				} catch (Exception e) { // Unable to parse procedureDate
					error = true
				}
			}
			if(error) {
				procedureInstance.errors.rejectValue("procedureDate", "validation.procedure.procedureDate.unparsable",
					[message(code: 'procedure.label', default: 'Procedure')] as Object[],

hbis/grails-app/views/procedure/_form.gsp
<%@ page import="hbis.Procedure" %>

<script type="text/javascript">
	$(document).ready(function() {
			$("#dateOfDeath").datepicker({dateFormat: 'mm/dd/yy'});
		})
</script>
<div class="leftFormColumn">
<div class="fieldcontain ${hasErrors(bean: procedureInstance, field: 'procedureName', 'error')} required">
	<label for="procedureName">
		<g:message code="procedure.procedureName.label" default="Procedure Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:select tabindex="1" id="procedureName" name="procedureName.id" from="${hbis.ProcedureName.list()}" optionKey="id" required="" value="${procedureInstance?.procedureName?.id}" class="many-to-one" noSelection="['null': '']"/>	
</div>

<div class="fieldcontain ${hasErrors(bean: procedureInstance, field: 'subProcedureName', 'error')}">
	<label for="subProcedureName">
		<g:message code="procedure.subProcedureName.label" default="Sub Procedure Name" />
	</label>
	<g:select tabindex="1" id="subProcedureName" name="subProcedureName.id" from="${hbis.SubProcedureName.list()}" optionKey="id" value="${procedureInstance?.subProcedureName?.id}" class="many-to-one" noSelection="['null': '']"/>	
</div>


<div class="fieldcontain ${hasErrors(bean: procedureInstance, field: 'procedureDate', 'error')} required">
	<label for="procedureDate">
		<g:message code="procedure.procedureDate.label" default="Procedure Date" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField tabindex="1" type="date" name="procedureDate" id="procedureDate" value="${formatDate(format:'MM/dd/yyyy',date:procedureInstance?.procedureDate)}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: procedureInstance, field: 'endTimeOfProcedure', 'error')}">
	<label for="endTimeOfProcedure">
		<g:message code="procedure.endTimeOfProcedure.label" default="End Time of Procedure(HHmm, example 1452)" />
	</label>
	<g:textField tabindex="1" type="date" name="endTimeOfProcedure" id="endTimeOfProcedure" value="${formatDate(format:'HHmm',date:procedureInstance?.endTimeOfProcedure)}"/>
</div>



<div class="fieldcontain ${hasErrors(bean: procedureInstance, field: 'procurementResult', 'error')} ">
	<label for="procurementResult">
		<g:message code="procedure.procurementResult.label" default="Procurement Result" />
	</label>
	<g:select tabindex="1" id="procurementResult" name="procurementResult.id" from="${hbis.ProcurementResult.list()}" optionKey="id" value="${procedureInstance?.procurementResult?.id}" class="many-to-one" default="none" noSelection="['null': '']"/>
</div>

<div class="fieldcontain ${hasErrors(bean: procedureInstance, field: 'patientAge', 'error')}">
	<label for="patientAge">
		<g:message code="procedure.patientAge.label" default="Patient Age" />
	</label>
	<g:field tabindex="1" name="patientAge" type="text" value="${procedureInstance.patientAge}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: procedureInstance, field: 'patientAgeUnit', 'error')} ">
	<label for="patientAgeUnit">
		<g:message code="procedure.patientAgeUnit.label" default="Patient Age Unit" />
	</label>
	<g:select tabindex="1" id="patientAgeUnit" name="patientAgeUnit.id" from="${hbis.AgeUnit.list()}" optionKey="id" value="${procedureInstance?.patientAgeUnit?.id}" class="many-to-one" noSelection="['null': '']"/>
</div>

<div class="fieldcontain ${hasErrors(bean: procedureInstance, field: 'chemoHistory', 'error')} ">
	<label for="chemoHistory">
		<g:message code="procedure.chemoHistory.label" default="Chemo History" />
	</label>
	<g:select tabindex="1" id="chemoHistory" name="chemoHistory.id" from="${hbis.YesNo.list()}" optionKey="id" value="${procedureInstance?.chemoHistory?.id}" class="many-to-one" noSelection="['null': '']"/>
</div>

<div class="fieldcontain ${hasErrors(bean: procedureInstance, field: 'chemoHistoryComments', 'error')}">
	<label for="chemoHistoryComments">
		<g:message code="procedure.chemoHistoryComments.label" default="Chemo History Comments" />
	</label>
	<g:textField tabindex="1" name="chemoHistoryComments" value="${procedureInstance?.chemoHistoryComments}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: procedureInstance, field: 'radiationHistory', 'error')} ">
	<label for="radiationHistory">
		<g:message code="procedure.radiationHistory.label" default="Radiation History" />
	</label>
	<g:select tabindex="1" id="radiationHistory" name="radiationHistory.id" from="${hbis.YesNo.list()}" optionKey="id" value="${procedureInstance?.radiationHistory?.id}" class="many-to-one" noSelection="['null': '']"/>
</div>

<div class="fieldcontain ${hasErrors(bean: procedureInstance, field: 'radiationHistoryComments', 'error')} ">
	<label for="radiationHistoryComments">
		<g:message code="procedure.radiationHistoryComments.label" default="Radiation History Comments" />
	</label>
	<g:textField tabindex="1" name="radiationHistoryComments" value="${procedureInstance?.radiationHistoryComments}"/>
</div>

</div> <!-- End Left Form Column -->

<div class="rightFormColumn">

<div class="fieldcontain ${hasErrors(bean: procedureInstance, field: 'roomNumber', 'error')} ">
	<label for="roomNumber">
		<g:message code="procedure.roomNumber.label" default="Room Number" />
		
	</label>
	<g:textField tabindex="1" name="roomNumber" value="${procedureInstance?.roomNumber}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: procedureInstance, field: 'dateOfDeath', 'error')} ">
	<label for="dateOfDeath">
		<g:message code="procedure.dateOfDeath.label" default="Date Of Death" />
	</label>
	<!--<g:datePicker name="dateOfDeath" precision="day"  value="${procedureInstance?.dateOfDeath}" default="none" noSelection="['null': '']" />-->
	<g:textField tabindex="1" type="date" name="dateOfDeath" id="dateOfDeath" value="${formatDate(format:'MM/dd/yyyy',date:procedureInstance?.dateOfDeath)}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: procedureInstance, field: 'procedureType', 'error')} required">
	<label for="procedureType">
		<g:message code="procedure.procedureType.label" default="Procedure Type" />
		<span class="required-indicator">*</span>
	</label>
	<g:select tabindex="1" id="procedureType" name="procedureType.id" from="${hbis.ProcedureType.list()}" optionKey="id" required="" value="${procedureInstance?.procedureType?.id}" class="many-to-one"/>
</div>

<div class="fieldcontain ${hasErrors(bean: procedureInstance, field: 'procedureEventInstitution', 'error')} required">
	<label for="procedureEventInstitution">
		<g:message code="procedure.procedureEventInstitution.label" default="Procedure Event Institution" />
		<span class="required-indicator">*</span>
	</label>
	<!-- Default value of OSU -->
	<g:select tabindex="1" id="procedureEventInstitution" name="procedureEventInstitution.id"  from="${hbis.Institution.list()}" optionKey="id" required="" value="${procedureInstance?.procedureEventInstitution?.id}" class="many-to-one" noSelection="['null': '']"/>
</div>

<div class="fieldcontain ${hasErrors(bean: procedureInstance, field: 'building', 'error')} ">
	<label for="building">
		<g:message code="procedure.building.label" default="Building" />
		
	</label>
	<g:textField tabindex="1" name="building" value="${procedureInstance?.building}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: procedureInstance, field: 'origin', 'error')} ">
	<label for="origin">
		<g:message code="procedure.origin.label" default="Origin" />
		
	</label>
	<g:select tabindex="1" id="origin" name="origin.id" from="${hbis.Origin.list()}" optionKey="id" value="${procedureInstance?.origin?.id}" class="many-to-one" noSelection="['null': '']"/>
</div>

<div class="fieldcontain ${hasErrors(bean: procedureInstance, field: 'medComments', 'error')} ">
	<label for="medComments">
		<g:message code="procedure.medComments.label" default="Med Comments" />
		
	</label>
	<g:textField tabindex="1" name="medComments" value="${procedureInstance?.medComments}"/>
</div>

<g:hiddenField name="patient.id" value="${procedureInstance?.patient?.id}"/>
</div> <!-- End Right Form Column -->

hbis/grails-app/views/procedure/amProcedureList.gsp
<%@ page import="hbis.Procedure" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'procedure.label', default: 'Procedure')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-procedure" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

		<div id="list-procedure" class="content scaffold-list" role="main">
			<h1>Procedures Added Today</h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<div class="allowTableOverflow"> <!-- Want to make sure table is scrollable on lower res monitors -->
			<table>
				<thead>
					<tr>
					
						<g:sortableColumn property="procedureDate" title="${message(code: 'procedure.procedureDate.label', default: 'Procedure Date')}" />
						
						<th><g:message code="patient.mrn.label" default="MRN" /></th>
						
						<th><g:message code="patient.lastName.label" default="Last Name" /></th>
					
						<th><g:message code="procedure.procedureType.label" default="Procedure Type" /></th>
					
						<th><g:message code="procedure.procedureName.label" default="Procedure Name" /></th>
						
						<th><g:message code="procedure.subProcedureName.label" default="Sub Procedure Name" /></th>
						
						<th><g:message code="procedure.roomNumber.label" default="Room" /></th>
						
						<th><g:message code="procedure.endTimeOfProcedure.label" default="End Time" /></th>
					
						<th><g:message code="procedure.procurementResult.label" default="Procurement Result" /></th>
						
						<th><g:message code="procedure.medComments.label" default="Med Comments" /></th>
						
						<th><g:message code="procedure.origin.label" default="Origin" /></th>
						
						<th><g:message code="patient.consent.label" default="Consent" /></th>
						
						<th></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${procedureInstanceList}" status="i" var="procedureInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${procedureInstance.id}"><g:formatDate format="MM/dd/yyyy" date="${procedureInstance.procedureDate}"/></g:link></td>
						
						<td><g:link controller="patient" action="show" id="${procedureInstance.patient.id}">${fieldValue(bean: procedureInstance, field: "patient.mrn")}</g:link></td>
						
						<td>${fieldValue(bean: procedureInstance, field: "patient.lastName")}</td>
					
						<td>${fieldValue(bean: procedureInstance, field: "procedureType")}</td>
					
						<td>${fieldValue(bean: procedureInstance, field: "procedureName")}</td>
						
						<td>${fieldValue(bean: procedureInstance, field: "subProcedureName")}</td>
						
						<td>${fieldValue(bean: procedureInstance, field: "roomNumber")}</td>
						
						<td><g:formatDate format="hh:mm aa" date="${procedureInstance.endTimeOfProcedure}"/></td>
					
						<td>${fieldValue(bean: procedureInstance, field: "procurementResult")}</td>
						
						<td>${fieldValue(bean: procedureInstance, field: "medComments")}</td>
						
						<td>${fieldValue(bean: procedureInstance, field: "origin")}</td>
						
						<td><g:if test="${procedureInstance?.patient?.consents}">
								<g:each in="${procedureInstance?.patient?.consents}" var="c">
									<g:if test="${c.protocols}">
										<g:each in="${c.protocols}" var="p">
											<g:link controller="protocol" action="show" id="${p.id}">${p?.encodeAsHTML()}</g:link><br>
										</g:each>
									</g:if>
								</g:each>
							</g:if></td>
						
						<td><g:link action="edit" id="${procedureInstance.id}">Edit</g:link></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			</div>
		</div>
		
		<div id="morningListReport">
			<h2>Morning List Report:</h2>
			<g:jasperReport
   						jasper="morning-list"
   						name="morning-list-${new Date().format('MMddyy')}"
   						controller="procedure"
   						action="morningListReport"
   						format="pdf, xls"
   						description=" "
   						delimiter=" ">
   						</g:jasperReport>
		</div>
		
		<g:form controller="patient" action="create">
		<div>
			<fieldset class="box"> <legend><strong>Search for Patient</strong></legend>
				MRN <g:remoteField name="mrn" controller="patient" action="performSearchMRN" paramName="mrn" update="divSearchMRN" value="" tabindex="1" />
			</fieldset>
		</div>
		
		<fieldset class="box"><legend><strong>Patient Search Results</strong></legend>
		<div id="divSearchMRN">
					<g:render template="/patient/searchMRNResult" var="patientInstance" collection="${patientList}" />
		</div>
		</fieldset>
		<div id="addNewPatient">
			<input type="submit" value="Add New Patient">
		</div>
		</g:form>
	</body>
</html>