hbis/grails-app/domain/hbis/QcResult.groovy
package hbis

class QcResult {
	String qcCode
	String qcPathologist //reviewed by
	Integer regionOfInterest
	BigDecimal regionOfInterestArea
	Integer percentNecrosis
	String linkPathReport
	String linkOverlayImage
	String linkSvsImage
	
	TissueQcMatch tissueQcMatch
	TissueType finalTissueType
	AnatomicSite finalPrimaryAnatomicSite
	Diagnosis finalDiagnosis
	SubDiagnosis finalSubDiagnosis
	ModDiagnosis finalModDiagnosis
	boolean goodForTma
	String pathologistComments
	Grade finalGrade
	Stage finalStage
	MolecularStatusEr finalMolecularStatusEr
	MolecularStatusPr finalMolecularStatusPr
	MolecularStatusHer2 finalMolecularStatusHer2
	QcFollowUpAction qcFollowUpAction
	
	Date dateCreated //check if they want to capture an actual completion date (other than insertion in the db)
	
	Specimen specimen
	//static belongsTo = [specimen: Specimen]
	
    static constraints = {
		qcCode(nullable:true)
		qcPathologist(nullable:true)
		regionOfInterest(nullable:true, min:0, max:100)
		regionOfInterestArea(nullable:true, scale:0)
		percentNecrosis(nullable:true, min:0, max:100)
		linkPathReport(nullable:true)
		linkOverlayImage(nullable:true)
		linkSvsImage(nullable:true)
		tissueQcMatch(nullable:true)
		finalPrimaryAnatomicSite(nullable:true)
		finalTissueType(nullable:true)
		finalDiagnosis(nullable:true)
		finalSubDiagnosis(nullable:true)
		finalModDiagnosis(nullable:true)
		goodForTma(nullable:true)
		pathologistComments(nullable:true)
		finalGrade(nullable:true)
		finalStage(nullable:true)
		finalMolecularStatusEr(nullable:true)
		finalMolecularStatusPr(nullable:true)
		finalMolecularStatusHer2(nullable:true)
		qcFollowUpAction(nullable:true)
    }
	
}

hbis/grails-app/views/qcResult/_form.gsp
<%@ page import="hbis.QcResult" %>



<div class="fieldcontain ${hasErrors(bean: qcResultInstance, field: 'qcCode', 'error')} ">
	<label for="qcCode">
		<g:message code="qcResult.qcCode.label" default="Qc Code" />
		
	</label>
	<g:textField name="qcCode" value="${qcResultInstance?.qcCode}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: qcResultInstance, field: 'qcPathologist', 'error')} ">
	<label for="qcPathologist">
		<g:message code="qcResult.qcPathologist.label" default="Qc Pathologist" />
		
	</label>
	<g:textField name="qcPathologist" value="${qcResultInstance?.qcPathologist}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: qcResultInstance, field: 'regionOfInterest', 'error')} ">
	<label for="regionOfInterest">
		<g:message code="qcResult.regionOfInterest.label" default="Region Of Interest" />
		
	</label>
	<g:field name="regionOfInterest" type="number" value="${qcResultInstance.regionOfInterest}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: qcResultInstance, field: 'regionOfInterestArea', 'error')} ">
	<label for="regionOfInterestArea">
		<g:message code="qcResult.regionOfInterestArea.label" default="Region Of Interest Area" />
		
	</label>
	<g:field name="regionOfInterestArea" type="number" value="${qcResultInstance.regionOfInterestArea}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: qcResultInstance, field: 'percentNecrosis', 'error')} ">
	<label for="percentNecrosis">
		<g:message code="qcResult.percentNecrosis.label" default="Percent Necrosis" />
		
	</label>
	<g:field name="percentNecrosis" type="number" value="${qcResultInstance.percentNecrosis}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: qcResultInstance, field: 'linkPathReport', 'error')} ">
	<label for="linkPathReport">
		<g:message code="qcResult.linkPathReport.label" default="Link Path Report" />
		
	</label>
	<g:textField name="linkPathReport" value="${qcResultInstance?.linkPathReport}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: qcResultInstance, field: 'linkImage', 'error')} ">
	<label for="linkImage">
		<g:message code="qcResult.linkImage.label" default="Link Image" />
		
	</label>
	<g:textField name="linkImage" value="${qcResultInstance?.linkImage}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: qcResultInstance, field: 'actualAnatomicSite', 'error')} ">
	<label for="actualAnatomicSite">
		<g:message code="qcResult.actualAnatomicSite.label" default="Actual Anatomic Site" />
		
	</label>
	<g:textField name="actualAnatomicSite" value="${qcResultInstance?.actualAnatomicSite}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: qcResultInstance, field: 'actualDiagnosis', 'error')} ">
	<label for="actualDiagnosis">
		<g:message code="qcResult.actualDiagnosis.label" default="Actual Diagnosis" />
		
	</label>
	<g:textField name="actualDiagnosis" value="${qcResultInstance?.actualDiagnosis}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: qcResultInstance, field: 'actualSubDiagnosis', 'error')} ">
	<label for="actualSubDiagnosis">
		<g:message code="qcResult.actualSubDiagnosis.label" default="Actual Sub Diagnosis" />
		
	</label>
	<g:textField name="actualSubDiagnosis" value="${qcResultInstance?.actualSubDiagnosis}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: qcResultInstance, field: 'actualModDiagnosis', 'error')} ">
	<label for="actualModDiagnosis">
		<g:message code="qcResult.actualModDiagnosis.label" default="Actual Mod Diagnosis" />
		
	</label>
	<g:textField name="actualModDiagnosis" value="${qcResultInstance?.actualModDiagnosis}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: qcResultInstance, field: 'goodForTMA', 'error')} ">
	<label for="goodForTMA">
		<g:message code="qcResult.goodForTMA.label" default="Good For TMA" />
		
	</label>
	<g:checkBox name="goodForTMA" value="${qcResultInstance?.goodForTMA}" />
</div>

<div class="fieldcontain ${hasErrors(bean: qcResultInstance, field: 'pathologistComments', 'error')} ">
	<label for="pathologistComments">
		<g:message code="qcResult.pathologistComments.label" default="Pathologist Comments" />
		
	</label>
	<g:textField name="pathologistComments" value="${qcResultInstance?.pathologistComments}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: qcResultInstance, field: 'specimen', 'error')} required">
	<label for="specimen">
		<g:message code="qcResult.specimen.label" default="Specimen" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="specimen" name="specimen.id" from="${hbis.Specimen.list()}" optionKey="id" required="" value="${qcResultInstance?.specimen?.id}" class="many-to-one"/>
</div>

hbis/grails-app/views/qcResult/create.gsp
<%@ page import="hbis.QcResult" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'qcResult.label', default: 'QcResult')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-qcResult" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

		<div id="create-qcResult" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${qcResultInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${qcResultInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form action="save" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

hbis/grails-app/views/qcResult/edit.gsp
<%@ page import="hbis.QcResult" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'qcResult.label', default: 'QcResult')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-qcResult" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

		<div id="edit-qcResult" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${qcResultInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${qcResultInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form method="post" >
				<g:hiddenField name="id" value="${qcResultInstance?.id}" />
				<g:hiddenField name="version" value="${qcResultInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" formnovalidate="" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

hbis/grails-app/views/qcResult/list.gsp
<%@ page import="hbis.QcResult" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'qcResult.label', default: 'QcResult')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-qcResult" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

		<div id="list-qcResult" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
				<thead>
					<tr>
					

hbis/grails-app/views/qcResult/show.gsp
<%@ page import="hbis.QcResult" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'qcResult.label', default: 'QcResult')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-qcResult" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

		<div id="show-qcResult" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list qcResult">
			
				<g:if test="${qcResultInstance?.qcCode}">
				<li class="fieldcontain">
					<span id="qcCode-label" class="property-label"><g:message code="qcResult.qcCode.label" default="Qc Code" /></span>
					
						<span class="property-value" aria-labelledby="qcCode-label"><g:fieldValue bean="${qcResultInstance}" field="qcCode"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${qcResultInstance?.qcPathologist}">
				<li class="fieldcontain">
					<span id="qcPathologist-label" class="property-label"><g:message code="qcResult.qcPathologist.label" default="Qc Pathologist" /></span>
					
						<span class="property-value" aria-labelledby="qcPathologist-label"><g:fieldValue bean="${qcResultInstance}" field="qcPathologist"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${qcResultInstance?.regionOfInterest}">
				<li class="fieldcontain">
					<span id="regionOfInterest-label" class="property-label"><g:message code="qcResult.regionOfInterest.label" default="Region Of Interest" /></span>
					
						<span class="property-value" aria-labelledby="regionOfInterest-label"><g:fieldValue bean="${qcResultInstance}" field="regionOfInterest"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${qcResultInstance?.regionOfInterestArea}">
				<li class="fieldcontain">
					<span id="regionOfInterestArea-label" class="property-label"><g:message code="qcResult.regionOfInterestArea.label" default="Region Of Interest Area" /></span>
					
						<span class="property-value" aria-labelledby="regionOfInterestArea-label"><g:fieldValue bean="${qcResultInstance}" field="regionOfInterestArea"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${qcResultInstance?.percentNecrosis}">
				<li class="fieldcontain">
					<span id="percentNecrosis-label" class="property-label"><g:message code="qcResult.percentNecrosis.label" default="Percent Necrosis" /></span>
					
						<span class="property-value" aria-labelledby="percentNecrosis-label"><g:fieldValue bean="${qcResultInstance}" field="percentNecrosis"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${qcResultInstance?.linkPathReport}">
				<li class="fieldcontain">
					<span id="linkPathReport-label" class="property-label"><g:message code="qcResult.linkPathReport.label" default="Link Path Report" /></span>
					
						<span class="property-value" aria-labelledby="linkPathReport-label"><g:fieldValue bean="${qcResultInstance}" field="linkPathReport"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${qcResultInstance?.linkImage}">
				<li class="fieldcontain">
					<span id="linkImage-label" class="property-label"><g:message code="qcResult.linkImage.label" default="Link Image" /></span>
					
						<span class="property-value" aria-labelledby="linkImage-label"><g:fieldValue bean="${qcResultInstance}" field="linkImage"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${qcResultInstance?.actualAnatomicSite}">
				<li class="fieldcontain">
					<span id="actualAnatomicSite-label" class="property-label"><g:message code="qcResult.actualAnatomicSite.label" default="Actual Anatomic Site" /></span>
					
						<span class="property-value" aria-labelledby="actualAnatomicSite-label"><g:fieldValue bean="${qcResultInstance}" field="actualAnatomicSite"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${qcResultInstance?.actualDiagnosis}">
				<li class="fieldcontain">
					<span id="actualDiagnosis-label" class="property-label"><g:message code="qcResult.actualDiagnosis.label" default="Actual Diagnosis" /></span>
					
						<span class="property-value" aria-labelledby="actualDiagnosis-label"><g:fieldValue bean="${qcResultInstance}" field="actualDiagnosis"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${qcResultInstance?.actualSubDiagnosis}">
				<li class="fieldcontain">
					<span id="actualSubDiagnosis-label" class="property-label"><g:message code="qcResult.actualSubDiagnosis.label" default="Actual Sub Diagnosis" /></span>
					
						<span class="property-value" aria-labelledby="actualSubDiagnosis-label"><g:fieldValue bean="${qcResultInstance}" field="actualSubDiagnosis"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${qcResultInstance?.actualModDiagnosis}">
				<li class="fieldcontain">
					<span id="actualModDiagnosis-label" class="property-label"><g:message code="qcResult.actualModDiagnosis.label" default="Actual Mod Diagnosis" /></span>
					
						<span class="property-value" aria-labelledby="actualModDiagnosis-label"><g:fieldValue bean="${qcResultInstance}" field="actualModDiagnosis"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${qcResultInstance?.goodForTMA}">
				<li class="fieldcontain">
					<span id="goodForTMA-label" class="property-label"><g:message code="qcResult.goodForTMA.label" default="Good For TMA" /></span>
					
						<span class="property-value" aria-labelledby="goodForTMA-label"><g:formatBoolean boolean="${qcResultInstance?.goodForTMA}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${qcResultInstance?.pathologistComments}">
				<li class="fieldcontain">
					<span id="pathologistComments-label" class="property-label"><g:message code="qcResult.pathologistComments.label" default="Pathologist Comments" /></span>
					
						<span class="property-value" aria-labelledby="pathologistComments-label"><g:fieldValue bean="${qcResultInstance}" field="pathologistComments"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${qcResultInstance?.dateCreated}">
				<li class="fieldcontain">
					<span id="dateCreated-label" class="property-label"><g:message code="qcResult.dateCreated.label" default="Date Created" /></span>
					
						<span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate date="${qcResultInstance?.dateCreated}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${qcResultInstance?.specimen}">
				<li class="fieldcontain">
					<span id="specimen-label" class="property-label"><g:message code="qcResult.specimen.label" default="Specimen" /></span>
					
						<span class="property-value" aria-labelledby="specimen-label"><g:link controller="specimen" action="show" id="${qcResultInstance?.specimen?.id}">${qcResultInstance?.specimen?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form>
				<fieldset class="buttons">
					<g:hiddenField name="id" value="${qcResultInstance?.id}" />
					<g:link class="edit" action="edit" id="${qcResultInstance?.id}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>