hbis/grails-app/domain/hbis/Consent.groovy
package hbis

class Consent {//Consent history as an entity?
	Date consentDate
	ConsentType consentType
	ConsentStatus status
	ConsentMethod method
	Date statusChangeDate
	String location
	String consenterFirstName
	String consenterLastName
	String consenterPhoneNumber
	String consenterEmail
	
	Patient patient
	static hasMany = [protocols: Protocol]

	String toString() {
		def toStringValue = "${id}" + ": " + "${consentType}"
		def protocolPrinted = false
		protocols.each { protocol ->
			if(protocolPrinted) { //Adding another protocol to the previous printed ones
				toStringValue += ", "
			}
			else { // No protocol printed yet
				toStringValue += ": "
			}
			toStringValue += protocol.toString()
			protocolPrinted = true
		}
		return toStringValue
		
	}
	
    static constraints = {
		consentType()
		status()
		method()
		statusChangeDate(nullable:true)
		location(nullable:true)
		consenterFirstName(nullable:true)
		consenterLastName(nullable:true)
		consenterPhoneNumber(nullable:true)
		consenterEmail(nullable:true)
    }
	
	static mapping = {
		//protocols(sort:'description', order:'asc') //Get error - default sort for associations[Consent->protocols] are not supported with unidirectional one to many relationships
	}

}

hbis/grails-app/domain/hbis/Invoice.groovy
package hbis

class Invoice {
	String attentionTo
	String institution
	String department
	String streetAddress1
	String streetAddress2
	String city
	String state
	String zipCode
	String country
	
	Date invoiceDate
	
	InvoiceBillingStatus billingStatus
	InvoicePaymentStatus paymentStatus
	PaymentMethod paymentMethod
	//String otherPaymentMethod? //Asked Tina about paymentMethod, and she suggested having an Other choice with text area
	Date paymentReceivedDate
	String paymentReceivedBy
	BigDecimal amountPaid
	Date lastInvoiceSentDate
	
	Investigator investigator
	
	static hasMany = [shippingCarts: ShippingCart]

    static constraints = {
		attentionTo(nullable:true)
		institution(nullable:true)
		department(nullable:true)
		streetAddress1(nullable:true)
		streetAddress2(nullable:true)
		city(nullable:true)
		state(nullable:true)
		zipCode(nullable:true)
		country(nullable:true)
		invoiceDate(nullable:true)
		billingStatus(nullable:true)
		paymentStatus(nullable:true)
		paymentMethod(nullable:true)
		paymentReceivedDate(nullable:true)
		paymentReceivedBy(nullable:true)
		amountPaid(nullable:true)
		lastInvoiceSentDate(nullable:true)
    }
	
	static mapping = {
		shippingCarts(sort:'id', order:'asc')
	}
	
	BigDecimal getTotalPrice() {
		def totalPrice = 0.00;
		this.shippingCarts.each { shippingCart ->
			totalPrice += shippingCart.getTotalPrice()
		}
		return totalPrice
	}
	
	Integer getNumberOfShippingCarts() {
		def numberOfShippingCarts = 0
		this.shippingCarts.each {
			numberOfShippingCarts++
		}
		return numberOfShippingCarts
	}
}

hbis/grails-app/domain/hbis/Patient.groovy
package hbis

class Patient { //change class name to Patient
	String mrn
	String firstName
	String middleInitial
	String lastName
	Gender gender
	Race race
	Date dateOfBirth
	Institution originInstitution
	
	static hasMany = [procedures: Procedure, consents:Consent]
	String toString() {
		"${mrn}" + " " + "${lastName}"
	}

    static constraints = {
		mrn(blank: false, unique: true, matches: /\d{9}/)  //Must be 9 digits
		firstName(nullable:true)
		middleInitial(nullable:true)
		lastName()
		gender(nullable:true)
		race(nullable:true)
		dateOfBirth(nullable:true)
		originInstitution(nullable:true)
    }
	
	static mapping = {
		procedures(sort:'procedureDate', order:'asc')
		consents(sort:'consentDate', order:'asc')
	}
}

hbis/grails-app/views/showDomainTemplates/_consent.gsp
<ul class="property-list consent">
	<li class="fieldcontain">
		<span id="consentType-label" class="property-label"><g:message code="consent.consentType.label" default="Consent Type: " /></span>
		<span class="property-value" aria-labelledby="consentType-label"><g:fieldValue bean="${consentInstance}" field="consentType"/></span>
		
		<span id="status-label" class="property-label"><g:message code="consent.status.label" default="Status: " /></span>
		<span class="property-value" aria-labelledby="status-label"><g:fieldValue bean="${consentInstance}" field="status"/></span>
		
		<span id="method-label" class="property-label"><g:message code="consent.method.label" default="Method: " /></span>
		<span class="property-value" aria-labelledby="method-label"><g:fieldValue bean="${consentInstance}" field="method"/></span>
		
		<g:if test="${consentInstance?.protocols}">
			<li class="fieldcontain">
				<span id="protocols-label" class="property-label"><g:message code="consent.protocols.label" default="Protocols" /></span>
				<g:each in="${consentInstance?.protocols?}" var="p">
					<span class="property-value" aria-labelledby="protocols-label"><g:link controller="protocol" action="show" id="${p.id}">${p?.encodeAsHTML()}</g:link></span>
				</g:each>
			</li>
		</g:if>
	</li>
			
	<li class="fieldcontain">
		<span id="consentDate-label" class="property-label"><g:message code="consent.consentDate.label" default="Consent Date: " /></span>
		<span class="property-value" aria-labelledby="consentDate-label"><g:formatDate date="${consentInstance?.consentDate}" /></span>
	</li>
	
	<li class="fieldcontain">
		<span id="consenterFirstName-label" class="property-label"><g:message code="consent.consenterFirstName.label" default="Consenter First Name: " /></span>
		<span class="property-value" aria-labelledby="consenterFirstName-label"><g:fieldValue bean="${consentInstance}" field="consenterFirstName"/></span>
		
		<span id="consenterLastName-label" class="property-label"><g:message code="consent.consenterLastName.label" default="Consenter Last Name: " /></span>
		<span class="property-value" aria-labelledby="consenterLastName-label"><g:fieldValue bean="${consentInstance}" field="consenterLastName"/></span>
	</li>
			
	<li class="fieldcontain">
		<span id="consenterPhoneNumber-label" class="property-label"><g:message code="consent.consenterPhoneNumber.label" default="Consenter Phone Number: " /></span>
		<span class="property-value" aria-labelledby="consenterPhoneNumber-label"><g:fieldValue bean="${consentInstance}" field="consenterPhoneNumber"/></span>
		
		<span id="consenterEmail-label" class="property-label"><g:message code="consent.consenterEmail.label" default="Consenter Email: " /></span>
		<span class="property-value" aria-labelledby="consenterEmail-label"><g:fieldValue bean="${consentInstance}" field="consenterEmail"/></span>
	</li>
			
	<li class="fieldcontain">
		<span id="location-label" class="property-label"><g:message code="consent.location.label" default="Location: " /></span>
		<span class="property-value" aria-labelledby="location-label"><g:fieldValue bean="${consentInstance}" field="location"/></span>
	</li>
	
	<li class="fieldcontain">
		<span id="statusChangeDate-label" class="property-label"><g:message code="consent.statusChangeDate.label" default="Status Change Date: " /></span>
		<span class="property-value" aria-labelledby="statusChangeDate-label"><g:formatDate date="${consentInstance?.statusChangeDate}" /></span>
	</li>
			
	<li class="fieldcontain">
		<span id="patient-label" class="property-label"><g:message code="consent.patient.label" default="Patient: " /></span>
		<span class="property-value" aria-labelledby="patient-label"><g:link controller="patient" action="show" id="${consentInstance?.patient?.id}">${consentInstance?.patient?.encodeAsHTML()}</g:link></span>
	</li>
			
</ul>

hbis/grails-app/views/showDomainTemplates/_familyHistory.gsp
<div class="leftShowColumn">
<ul class="property-list familyHistory">
	<li class="fieldcontain">
		<span id="relative-label" class="property-label"><g:message code="familyHistory.relative.label" default="Relative" /></span>
		<span class="property-value" aria-labelledby="relative-label"><g:fieldValue bean="${familyHistoryInstance}" field="relative"/></span>
	</li>
	<li class="fieldcontain">
		<span id="diagnosis-label" class="property-label"><g:message code="familyHistory.diagnosis.label" default="Diagnosis" /></span>
		<span class="property-value" aria-labelledby="diagnosis-label"><g:link controller="diagnosis" action="show" id="${familyHistoryInstance?.diagnosis?.id}">${familyHistoryInstance?.diagnosis?.encodeAsHTML()}</g:link></span>
	</li>
	<li class="fieldcontain">
		<span id="chartReview-label" class="property-label"><g:message code="familyHistory.chartReview.label" default="Chart Review" /></span>
		<span class="property-value" aria-labelledby="chartReview-label"><g:link controller="chartReview" action="show" id="${familyHistoryInstance?.chartReview?.id}">${familyHistoryInstance?.chartReview?.encodeAsHTML()}</g:link></span>
	</li>
</ul>
</div>

hbis/grails-app/views/showDomainTemplates/_invoice.gsp
<ul class="property-list invoice">
	<li class="fieldcontain">
		<span id="investigator-label" class="property-label"><g:message code="invoice.investigator.label" default="Investigator" /></span>
		<span class="property-value" aria-labelledby="investigator-label"><g:link controller="investigator" action="show" id="${invoiceInstance?.investigator?.id}">${invoiceInstance?.investigator?.encodeAsHTML()}</g:link></span>
	</li>
	
	<li class="fieldcontain">
		<span id="attentionTo-label" class="property-label"><g:message code="invoice.attentionTo.label" default="Attention To" /></span>
		<span class="property-value" aria-labelledby="attentionTo-label"><g:fieldValue bean="${invoiceInstance}" field="attentionTo"/></span>
	</li>
	
	<li class="fieldcontain">
		<span id="institution-label" class="property-label"><g:message code="invoice.institution.label" default="Institution" /></span>
		<span class="property-value" aria-labelledby="institution-label"><g:fieldValue bean="${invoiceInstance}" field="institution"/></span>
	</li>
	
	<li class="fieldcontain">
		<span id="department-label" class="property-label"><g:message code="invoice.department.label" default="Department" /></span>
		<span class="property-value" aria-labelledby="department-label"><g:fieldValue bean="${invoiceInstance}" field="department"/></span>
	</li>
	
	<li class="fieldcontain">
		<span id="streetAddress1-label" class="property-label"><g:message code="invoice.streetAddress1.label" default="Street Address 1" /></span>
		<span class="property-value" aria-labelledby="streetAddress1-label"><g:fieldValue bean="${invoiceInstance}" field="streetAddress1"/></span>
	</li>
	
	<li class="fieldcontain">
		<span id="streetAddress2-label" class="property-label"><g:message code="invoice.streetAddress2.label" default="Street Address 2" /></span>
		<span class="property-value" aria-labelledby="streetAddress2-label"><g:fieldValue bean="${invoiceInstance}" field="streetAddress2"/></span>
	</li>
	
	<li class="fieldcontain">
		<span id="city-label" class="property-label"><g:message code="invoice.city.label" default="City" /></span>
		<span class="property-value" aria-labelledby="city-label"><g:fieldValue bean="${invoiceInstance}" field="city"/></span>
	</li>
	
	<li class="fieldcontain">
		<span id="state-label" class="property-label"><g:message code="invoice.state.label" default="State" /></span>
		<span class="property-value" aria-labelledby="state-label"><g:fieldValue bean="${invoiceInstance}" field="state"/></span>
	</li>
	
	<li class="fieldcontain">
		<span id="zipCode-label" class="property-label"><g:message code="invoice.zipCode.label" default="Zip Code" /></span>
		<span class="property-value" aria-labelledby="zipCode-label"><g:fieldValue bean="${invoiceInstance}" field="zipCode"/></span>
	</li>
	
	<li class="fieldcontain">
		<span id="country-label" class="property-label"><g:message code="invoice.country.label" default="Country" /></span>
		<span class="property-value" aria-labelledby="country-label"><g:fieldValue bean="${invoiceInstance}" field="country"/></span>
	</li>
	
	<li class="fieldcontain">
		<span id="invoiceDate-label" class="property-label"><g:message code="invoice.invoiceDate.label" default="Invoice Date" /></span>
		<span class="property-value" aria-labelledby="invoiceDate-label"><g:formatDate date="${invoiceInstance?.invoiceDate}" /></span>
	</li>
	
	<li class="fieldcontain">
		<span id="lastInvoiceSentDate-label" class="property-label"><g:message code="invoice.lastInvoiceSentDate.label" default="Last Invoice Sent Date" /></span>
		<span class="property-value" aria-labelledby="lastInvoiceSentDate-label"><g:formatDate date="${invoiceInstance?.lastInvoiceSentDate}" /></span>
	</li>
	
	<li class="fieldcontain">
		<span id="billingStatus-label" class="property-label"><g:message code="invoice.billingStatus.label" default="Billing Status" /></span>
		<span class="property-value" aria-labelledby="billingStatus-label"><g:fieldValue bean="${invoiceInstance}" field="billingStatus"/></span>
	</li>
			
	<li class="fieldcontain">
		<span id="paymentStatus-label" class="property-label"><g:message code="invoice.paymentStatus.label" default="Payment Status" /></span>
		<span class="property-value" aria-labelledby="paymentStatus-label"><g:fieldValue bean="${invoiceInstance}" field="paymentStatus"/></span>
	</li>
			
	<li class="fieldcontain">
		<span id="paymentReceivedDate-label" class="property-label"><g:message code="invoice.paymentReceivedDate.label" default="Payment Received Date" /></span>
		<span class="property-value" aria-labelledby="paymentReceivedDate-label"><g:formatDate date="${invoiceInstance?.paymentReceivedDate}" /></span>
	</li>
	
	<li class="fieldcontain">
		<span id="paymentReceivedBy-label" class="property-label"><g:message code="invoice.paymentReceivedBy.label" default="Payment Received By" /></span>
		<span class="property-value" aria-labelledby="paymentReceivedBy-label"><g:fieldValue bean="${invoiceInstance}" field="paymentReceivedBy" /></span>
	</li>
	 
	<li class="fieldcontain">
		<span id="shippingCarts-label" class="property-label"><g:message code="invoice.shippingCarts.label" default="Shipping Carts" /></span>
		<g:each in="${invoiceInstance.shippingCarts}" var="s">
			<span class="property-value" aria-labelledby="shippingCarts-label"><g:link controller="shippingCart" action="show" id="${s.id}">${s?.encodeAsHTML()}</g:link></span>
		</g:each>
	</li>	
	
</ul>

hbis/grails-app/views/showDomainTemplates/_medicalHistory.gsp
<div class="leftShowColumn">
<ul class="property-list medicalHistory">
	<li class="fieldcontain">
		<span id="cancer-label" class="property-label"><g:message code="medicalHistory.cancer.label" default="Cancer" /></span>
		<span class="property-value" aria-labelledby="cancer-label"><g:link controller="primaryMets" action="show" id="${medicalHistoryInstance?.cancer?.id}">${medicalHistoryInstance?.cancer?.encodeAsHTML()}</g:link></span>
	</li>
	<li class="fieldcontain">
		<span id="status-label" class="property-label"><g:message code="medicalHistory.status.label" default="Status" /></span>
		<span class="property-value" aria-labelledby="status-label"><g:link controller="medicalStatus" action="show" id="${medicalHistoryInstance?.status?.id}">${medicalHistoryInstance?.status?.encodeAsHTML()}</g:link></span>
	</li>
	<li class="fieldcontain">
		<span id="diagnosis-label" class="property-label"><g:message code="medicalHistory.diagnosis.label" default="Diagnosis" /></span>
		<span class="property-value" aria-labelledby="diagnosis-label"><g:link controller="diagnosis" action="show" id="${medicalHistoryInstance?.diagnosis?.id}">${medicalHistoryInstance?.diagnosis?.encodeAsHTML()}</g:link></span>
	</li>
	<li class="fieldcontain">
		<span id="stage-label" class="property-label"><g:message code="medicalHistory.stage.label" default="Stage" /></span>
		<span class="property-value" aria-labelledby="stage-label"><g:fieldValue bean="${medicalHistoryInstance}" field="stage"/></span>
	</li>
	<li class="fieldcontain">
		<span id="chartReview-label" class="property-label"><g:message code="medicalHistory.chartReview.label" default="Chart Review" /></span>
		<span class="property-value" aria-labelledby="chartReview-label"><g:link controller="chartReview" action="show" id="${medicalHistoryInstance?.chartReview?.id}">${medicalHistoryInstance?.chartReview?.encodeAsHTML()}</g:link></span>
	</li>
</ul>
</div>

hbis/grails-app/views/showDomainTemplates/_medication.gsp
<div class="leftShowColumn">
<ul class="property-list medication">
	<li class="fieldcontain">
		<span id="medicationName-label" class="property-label"><g:message code="medication.medicationName.label" default="Medication Name" /></span>
		<span class="property-value" aria-labelledby="medicationName-label"><g:fieldValue bean="${medicationInstance}" field="medicationName"/></span>
	</li>
	<li class="fieldcontain">
		<span id="doseMg-label" class="property-label"><g:message code="medication.doseMg.label" default="Dose Mg" /></span>
		<span class="property-value" aria-labelledby="doseMg-label"><g:fieldValue bean="${medicationInstance}" field="doseMg"/></span>
	</li>
	<li class="fieldcontain">
		<span id="doseOther-label" class="property-label"><g:message code="medication.doseOther.label" default="Dose Other" /></span>
		<span class="property-value" aria-labelledby="doseOther-label"><g:fieldValue bean="${medicationInstance}" field="doseOther"/></span>
	</li>
	<li class="fieldcontain">
		<span id="frequency-label" class="property-label"><g:message code="medication.frequency.label" default="Frequency" /></span>
		<span class="property-value" aria-labelledby="frequency-label"><g:fieldValue bean="${medicationInstance}" field="frequency"/></span>
	</li>
	<li class="fieldcontain">
		<span id="status-label" class="property-label"><g:message code="medication.status.label" default="Status" /></span>
		<span class="property-value" aria-labelledby="status-label"><g:link controller="medicalStatus" action="show" id="${medicationInstance?.status?.id}">${medicationInstance?.status?.encodeAsHTML()}</g:link></span>
	</li>
	<li class="fieldcontain">
		<span id="chartReview-label" class="property-label"><g:message code="medication.chartReview.label" default="Chart Review" /></span>
		<span class="property-value" aria-labelledby="chartReview-label"><g:link controller="chartReview" action="show" id="${medicationInstance?.chartReview?.id}">${medicationInstance?.chartReview?.encodeAsHTML()}</g:link></span>
	</li>
</ul>
</div>

hbis/grails-app/views/showDomainTemplates/_patient.gsp
<div class="leftShowColumn">
<ul class="property-list patient">
	<li class="fieldcontain">
		<span id="mrn-label" class="property-label"><g:message code="patient.mrn.label" default="MRN" /></span>
		<span class="property-value" aria-labelledby="mrn-label"><g:fieldValue bean="${patientInstance}" field="mrn"/></span>
	</li>
	<li class="fieldcontain">
		<span id="firstName-label" class="property-label"><g:message code="patient.firstName.label" default="First Name" /></span>
		<span class="property-value" aria-labelledby="firstName-label"><g:fieldValue bean="${patientInstance}" field="firstName"/></span>
	</li>
	<li class="fieldcontain">		
		<span id="middleInitial-label" class="property-label"><g:message code="patient.middleInitial.label" default="Middle Initial" /></span>
		<span class="property-value" aria-labelledby="middleInitial-label"><g:fieldValue bean="${patientInstance}" field="middleInitial"/></span>
	</li>
	<li class="fieldcontain">		
		<span id="lastName-label" class="property-label"><g:message code="patient.lastName.label" default="Last Name" /></span>
		<span class="property-value" aria-labelledby="lastName-label"><g:fieldValue bean="${patientInstance}" field="lastName"/></span>
	</li>
</ul>
</div>
<div class="middleShowColumn">
<ul class="property-list patient">
	<li class="fieldcontain">
		<span id="gender-label" class="property-label"><g:message code="patient.gender.label" default="Gender" /></span>
		<span class="property-value" aria-labelledby="gender-label"><g:link controller="gender" action="show" id="${patientInstance?.gender?.id}">${patientInstance?.gender?.encodeAsHTML()}</g:link></span>
	</li>
	<li class="fieldcontain">
		<span id="race-label" class="property-label"><g:message code="patient.race.label" default="Race" /></span>
		<span class="property-value" aria-labelledby="race-label"><g:link controller="race" action="show" id="${patientInstance?.race?.id}">${patientInstance?.race?.encodeAsHTML()}</g:link></span>
	</li>
	<li class="fieldcontain">
		<span id="dateOfBirth-label" class="property-label"><g:message code="patient.dateOfBirth.label" default="Date Of Birth" /></span>
		<span class="property-value" aria-labelledby="dateOfBirth-label"><g:formatDate format="MM/dd/yyyy" date="${patientInstance?.dateOfBirth}"/></span>
	</li>
	<g:if test="${patientInstance?.procedures}">
		<li class="fieldcontain">
			<span id="procedures-label" class="property-label"><g:message code="patient.procedures.label" default="Procedures" /></span>
			<g:each in="${patientInstance?.procedures?}" var="p">
				<span class="property-value" aria-labelledby="procedures-label"><g:link controller="procedure" action="show" id="${p.id}">${p?.encodeAsHTML()}</g:link></span>
			</g:each>
		</li>
	</g:if>
	<g:if test="${patientInstance?.consents}">
		<li class="fieldcontain">
			<span id="consents-label" class="property-label"><g:message code="patient.consents.label" default="Consents" /></span>
			<g:each in="${patientInstance?.consents?}" var="c">
				<span class="property-value" aria-labelledby="consents-label"><g:link controller="consent" action="show" id="${c.id}">${c?.encodeAsHTML()}</g:link></span>
			</g:each>
		</li>
	</g:if>
</ul>
</div>

hbis/grails-app/views/showDomainTemplates/_surgicalHistory.gsp
<div class="leftShowColumn">
<ul class="property-list surgicalHistory">
	<li class="fieldcontain">
		<span id="anesthetics-label" class="property-label"><g:message code="surgicalHistory.anesthetics.label" default="Anesthetics" /></span>
		<span class="property-value" aria-labelledby="anesthetics-label"><g:fieldValue bean="${surgicalHistoryInstance}" field="anesthetics"/></span>
	</li>
	
	<li class="fieldcontain">
		<span id="forBiosample-label" class="property-label"><g:message code="surgicalHistory.forBiosample.label" default="For Biosample" /></span>
		<span class="property-value" aria-labelledby="forBiosample-label"><g:link controller="yesNo" action="show" id="${surgicalHistoryInstance?.forBiosample?.id}">${surgicalHistoryInstance?.forBiosample?.encodeAsHTML()}</g:link></span>
	</li>
	
	<li class="fieldcontain">
		<span id="procedure-label" class="property-label"><g:message code="surgicalHistory.procedure.label" default="Procedure" /></span>
		<span class="property-value" aria-labelledby="procedure-label"><g:link controller="procedureName" action="show" id="${surgicalHistoryInstance?.procedure?.id}">${surgicalHistoryInstance?.procedure?.encodeAsHTML()}</g:link></span>
	</li>

	<li class="fieldcontain">
		<span id="chartReview-label" class="property-label"><g:message code="surgicalHistory.chartReview.label" default="Chart Review" /></span>
		<span class="property-value" aria-labelledby="chartReview-label"><g:link controller="chartReview" action="show" id="${surgicalHistoryInstance?.chartReview?.id}">${surgicalHistoryInstance?.chartReview?.encodeAsHTML()}</g:link></span>
	</li>
</ul>
</div>

hbis/grails-app/views/showDomainTemplates/_tissueRequest.gsp
<ul class="property-list tissueRequest">
	<li class="fieldcontain">
		<span id="name-label" class="property-label"><g:message code="tissueRequest.name.label" default="Name" /></span>
		<span class="property-value" aria-labelledby="name-label"><g:fieldValue bean="${tissueRequestInstance}" field="name"/></span>
	</li>
			
	<li class="fieldcontain">
		<span id="status-label" class="property-label"><g:message code="tissueRequest.status.label" default="Status" /></span>
		<span class="property-value" aria-labelledby="status-label"><g:fieldValue bean="${tissueRequestInstance}" field="status"/></span>
	</li>
			
	<li class="fieldcontain">
		<span id="tissueRequestTissueQuestId-label" class="property-label"><g:message code="tissueRequest.tissueRequestTissueQuestId.label" default="Tissue Request Tissue Quest ID" /></span>
		<span class="property-value" aria-labelledby="tissueRequestTissueQuestId-label"><g:fieldValue bean="${tissueRequestInstance}" field="tissueRequestTissueQuestId"/></span>
	</li>
				
	<li class="fieldcontain">
		<span id="projectTissueQuestId-label" class="property-label"><g:message code="tissueRequest.projectTissueQuestId.label" default="Project Tissue Quest ID" /></span>
		<span class="property-value" aria-labelledby="projectTissueQuestId-label">${tissueRequestInstance?.projectTissueQuestId}</span>
	</li>
			
	<li class="fieldcontain">
		<span id="contactMethod-label" class="property-label"><g:message code="tissueRequest.contactMethod.label" default="Contact Method" /></span>
		<span class="property-value" aria-labelledby="contactMethod-label"><g:fieldValue bean="${tissueRequestInstance}" field="contactMethod"/></span>
	</li>
</ul>